version: "3.8"

services:
  backend-core:
    image: backend-base
    pull_policy: never
    env_file:
      - .env
    build:
      context: backend
      dockerfile: Dockerfile.dev
      args:
        - DEV_MODE=true
    container_name: backend-core
    volumes:
      - ./backend/:/code/
    command:
      - "uvicorn"
      - "main:app"
      - "--reload"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "5050"
      - "--workers"
      - "6"
    restart: always

    ports:
      - 5050:5050
      - 5678:5678 # debug port

  redis:
    image: redis:latest@sha256:11c3e418c29672341be9a8e3015d96f05b88e5ad58829885d36f8342b4da13c2
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  worker:
    pull_policy: never
    image: backend-base
    env_file:
      - .env
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: worker
    # volumes:
    #   - ./backend/:/code/
    command: >
      /bin/sh -c "
      watchmedo auto-restart -d . -p '*.py' --recursive -- celery -A celery_worker worker -l info
      "
    restart: always
    depends_on:
      - redis

  beat:
    image: backend-base
    pull_policy: never
    env_file:
      - .env
    build:
      context: backend
      dockerfile: Dockerfile

    container_name: beat
    command: >
      /bin/sh -c "
      watchmedo auto-restart -d . -p '*.py' --recursive -- celery -A celery_worker beat -l info
      "
    restart: always
    depends_on:
      - redis

  flower:
    image: backend-base
    pull_policy: never
    env_file:
      - .env
    build:
      context: backend
      dockerfile: Dockerfile

    container_name: flower
    command: celery -A celery_worker flower -l info --port=5555
    restart: always
    depends_on:
      - redis
      - worker
      - beat
    ports:
      - 5555:5555
